### ISSUE TITLE
Slow start with quantized embeddings

### ISSUE THREAD

**Issue by danieldk** [stickeritis/sticker#119]
sticker uses the average of all embeddings for the unknown embedding. However, this has a bad side-effect for quantized embeddings. Since all the embeddings in the embedding matrix are reconstructed, loading models takes quite a while.

Possible workarounds:

* Precompute the unknown embedding and add it to the embedding matrix. I dislike this somewhat, since sticker would need specially prepared matrices again.
* Precompute the unknown embedding and store it somewhere outside the embedding matrix. Breaks existing models.
* Precompute the unknown embedding over a sample of the embeddings.
* Maybe it's enough to average all subquantizers, since they are the centroids of the embeddings? This would be very cheap. Problem: the original embeddings may not be distributed evenly over the clusters.

@twuebi @sebpuetz any opinions?

**Comment by danieldk** [comment]
An implementation of the fourth idea in #120. Haven't empirically tested this yet.

**Comment by danieldk** [comment]
Tested on a model, there is no difference in accuracy. Of course, I don't know yet how much the unknown embedding is used at all (given subword units).

**Comment by sebpuetz** [comment]
I think the 4th version is the cleanest. Fwiw, I'd expect the actual value of the unknown embedding vector to not really matter as long as it's constant, so you might even get away with l2 normalizing a vector of 1s ;)

**Comment by danieldk** [comment]
> I think the 4th version is the cleanest. Fwiw, I'd expect the actual value of the unknown embedding vector to not really matter as long as it's constant, so you might even get away with l2 normalizing a vector of 1s ;)

Indeed, it must be some point that is not to similar to any particular embedding. My worry here are existing models. If the models were trained with unknown as the average embedding and then during prediction the average quantizers are used, this may result in different embeddings, and thus possibly different predictions.

However, it may as well be that the unknown embedding is not even used during training with subword units, which I'll check now.

For new models, it shouldn't matter.

**Comment by danieldk** [comment]
Checked: none of the tokens in tdz actually results in the unknown embedding for the German word embeddings that I have used so far.

**Comment by danieldk** [comment]
Difference with the PR:

~~~
# Before:
% echo | time target/release/sticker-tag /nix/store/rkqydriai1d33d9pdwr41v509fpcwclf-sticker-model-de-pos-ud-20190821/share/sticker/models/de-pos-ud/sticker.conf
target/release/sticker-tag   15.22s user 0.25s system 99% cpu 15.493 total

# After:
% echo | time target/release/sticker-tag /nix/store/rkqydriai1d33d9pdwr41v509fpcwclf-sticker-model-de-pos-ud-20190821/share/sticker/models/de-pos-ud/sticker.conf
target/release/sticker-tag   0.48s user 0.25s system 97% cpu 0.741 total
~~~

(Background: I am working on a small visualization tool, and I was getting annoyed by the 30 second load time of tagging + dep parsing models.)
