### ISSUE TITLE
Batch size in config

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#151]
Changing the batch size on the fly is a nice convenience when experimenting. Does something speak against moving it out of the config file?

**Comment by danieldk** [comment]
Actually, it is already an option for *pipeline* commands (`tag` and `server`), the configuration file is ignored. I would be completely in favor of doing the same for training commands.

If we remove it though, we should make it optional in the config and give a warning when it is still in the configuration (like `read_ahead` now).

**Comment by danieldk** [comment]
I'll assign myself for this ;).
