### ISSUE TITLE
Bump finalfusion dependency

### ISSUE THREAD

**Issue by sebpuetz** [stickeritis/sticker#177]
Explicit vocabs are unknown to sticker

**Comment by sebpuetz** [comment]
Requires:
- bump ndarray dep in `ndarray-tensorflow` and release a new version (or reference git versino)
- bump ndarray dep in `sticker`
- bump finalfusion dependency in `sticker`

**Comment by sebpuetz** [comment]
@danieldk https://github.com/danieldk/ndarray-tensorflow/pull/3 adding this here because you're not watching `ndarray-tensorflow`.

**Comment by danieldk** [comment]
Fixed! Unfortunately, I saw your PR too late :(.
