### ISSUE TITLE
Continue training

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#46]
Providing an option to continue training by loading a graph with parameters could provide two benefits:

1. quality of life improvement
2. allows for pre-training (with the same targets)
__________________________________________________________________
Changes this would entail:

* add `load_weights` to `TaggerTrainer` (pretty much exists in `Tagger::load_weights`)
* add indicator whether training should restart or continue 
(`sticker.conf:model:parameters == ""` for random weights & `sticker.conf:model:parameters == "epoch-x"` for loading weights  or flag?)
__________________________________________________________________
For more elaborate pre-training schemes, more changes would be necessary.

**Comment by danieldk** [comment]
Yep, I'd need this too with the pretraining experiments that I'm planning to do soon. I'll assign it to myself ;).

**Comment by danieldk** [comment]
For continuing, I think we could just add an option `--continue` to `sticker-train`? This would then load the specified parameters.

**Comment by twuebi** [comment]
Sounds got to me

**Comment by danieldk** [comment]
Added in f6530335f11b7ac77cdbc0e27014131029b89f56.
