### ISSUE TITLE
Option to only save with improvements

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#65]
Currently, we keep all saved model files. With ~100 epochs per model, this produces a pretty big amount of files where the size depends on model type / size.

It would be nice to have an option to only save the new parameters if `cur_performance > best_performance` or to only keep the last `n_patience` checkpoints.

**Comment by danieldk** [comment]
Working on it. Requires a bit of a rewrite of the savers, because they get too bloated otherwise.
