### ISSUE TITLE
Tensorboard broken with tf 1.14

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker#86]
https://github.com/tensorflow/tensorflow/commit/826027dbd4277a2636fc2935ed245700fd01e7cd#diff-335a6620279c6fa5d7f70c37c91265a3

this broke our `_create_file_writer_generic_type` in `vendored.py`, it was introduced with Tensorflow 1.14. I'm looking into it.

**Comment by twuebi** [comment]
~~~python
def _create_file_writer_generic_type(logdir,
                                    name="logdir",
                                    max_queue=None,
                                    flush_millis=None,
                                    filename_suffix=None):
    """
    This method mirrors `tensorflow.contrib.summary.create_file_writer`. Unlike
    `summary.create_file_writer`, this method accepts a placeholder as `logdir`.
    """
    from tensorflow.python.ops.summary_ops_v2 import ResourceSummaryWriter
    from tensorflow.python.ops.gen_summary_ops import create_summary_file_writer
    import functools
    logdir = tf.convert_to_tensor(logdir)
    with tf.device("cpu:0"):
        if max_queue is None:
            max_queue = tf.constant(10)
        if flush_millis is None:
            flush_millis = tf.constant(2 * 60 * 1000)
        if filename_suffix is None:
            filename_suffix = tf.constant(".v2")
        return ResourceSummaryWriter(
            shared_name=name,
            init_op_fn=functools.partial(create_summary_file_writer,
            logdir=logdir,
            max_queue=max_queue,
            flush_millis=flush_millis,
            filename_suffix=filename_suffix))
~~~

would fix the issue. 
________________________________________________________________

This is problematic since it would break backward compatibility with users on Tensorflow < 1.14. I guess there's an ugly workaround along these lines:

~~~python
    from pkg_resources import parse_version
    if parse_version(tf.VERSION) >=  "1.14":
        from tensorflow.python.ops.summary_ops_v2 import ResourceSummaryWriter
        return ResourceSummaryWriter(
                shared_name=name,
                init_op_fn=functools.partial(create_summary_file_writer,
                logdir=logdir,
                max_queue=max_queue,
                flush_millis=flush_millis,
                filename_suffix=filename_suffix))
    else:
        from tensorflow.python.ops.gen_summary_ops import create_summary_file_writer
        return _make_summary_writer(
             name,
             create_summary_file_writer,
            logdir=logdir,
            max_queue=max_queue,
            flush_millis=flush_millis,
            filename_suffix=filename_suffix)
~~~


As far as I can tell, the breaking changes only happened on the python side, summary writing with the fix and `libtensorflow` < 1.14 still works.

@danieldk what do you think?

**Comment by danieldk** [comment]
Such an `if` block for different behavior for different version seems ok to me. Probably not something we want to maintain in the long term, but it will take some months before everyone is on 1.14.

Nice that they are doing a 1.14 version!

**Comment by twuebi** [comment]
> Nice that they are doing a 1.14 version!

Seems to be moving towards object-oriented 2.0 without much consideration for graph use. It's gonna be interesting how the C-API will look like post 2.0.

**Comment by twuebi** [comment]
> It's gonna be interesting how the C-API will look like post 2.0.

https://github.com/tensorflow/rust/pull/212 seems like we may get eager or graph construction in rust at some point.
